x-logging: &x-logging
  logging:
    driver: json-file
    options:
      max-file: '5'
      max-size: '10m'

services:
  traefik:
    image: traefik:v2.11
    container_name: appwrite-traefik
    <<: *x-logging
    command:
      - "--entrypoints.appwrite_web.address=:80"
      - "--entrypoints.appwrite_websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - appwrite

  appwrite:
    image: appwrite/appwrite:1.6.1
    container_name: appwrite
    <<: *x-logging
    environment:
      - _APP_ENV=production
      - _APP_DOMAIN=tuodominio.com
      - _APP_DOMAIN_TARGET=tuodominio.com
      - _APP_REDIS_HOST=redis
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_USER=appwriteuser
      - _APP_DB_PASS=your_secure_password  # Match MYSQL_PASSWORD above
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_RETRIES=20  # Increase from default 10
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - appwrite

  mariadb:
    image: mariadb:10.11
    container_name: appwrite-mariadb
    <<: *x-logging
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=appwrite
      - MYSQL_USER=appwriteuser
      - MYSQL_PASSWORD=your_secure_password  # Must match Appwrite's _APP_DB_PASS
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [
        "CMD", "mysqladmin", "ping",
        "-uappwriteuser", "-p$$MYSQL_PASSWORD"  # Use appwriteuser credentials
      ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - appwrite

  redis:
    image: redis:7.2.4-alpine
    container_name: appwrite-redis
    <<: *x-logging
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - appwrite

volumes:
  mariadb_data:
  redis_data:

networks:
  appwrite:
    driver: bridge
