
x-logging: &x-logging
  logging:
    driver: json-file
    options:
      max-file: '5'
      max-size: '10m'

services:
  traefik:
    image: traefik:v2.11
    container_name: appwrite-traefik
    <<: *x-logging
    ports:
      - "8080:80"    # Modificato per evitare conflitti porte basse
      - "4430:443"    # Usa 4430 invece di 443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

  appwrite:
    image: appwrite/appwrite:1.6.1
    <<: *x-logging
    environment:
      - _APP_ENV=production
      - _APP_DOMAIN=tuodominio.com
      - _APP_DOMAIN_TARGET=tuodominio.com
      - _APP_REDIS_HOST=redis
      - _APP_DB_HOST=mariadb
      - _APP_DB_USER=appwriteuser
      - _APP_DB_PASS=StrongPassword123!
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:10.11
    <<: *x-logging
    environment:
      - MYSQL_ROOT_PASSWORD=RootSecurePassword456!
      - MYSQL_DATABASE=appwrite
      - MYSQL_USER=appwriteuser
      - MYSQL_PASSWORD=StrongPassword123!
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:7.2.4-alpine
    <<: *x-logging
    volumes:
      - redis_data:/data

volumes:
  mariadb_data:
  redis_data: